version: "3.8"

services:
  webapp:
    image: victor559/webapp:latest # Use your Docker Hub image
    ports:
      - "3000:3000"
    environment:
      MYSQL_URL: mysql://root:root@database:3306/database
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: Victor
      MYSQL_PASSWORD: passwd
    ports:
      - "3307:3306"
    volumes:
      - MySQLDatabase:/var/lib/mysql

  tests:
    image: victor559/webapp:latest
    environment:
      API_URL: http://webapp:3000
    depends_on:
      - webapp
      - database
    command: yarn test

volumes:
  MySQLDatabase:
