name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install
        working-directory: ./webapp

      - name: Lint codebase
        env: # Set environment variables for the linting step
          ESLINT_USE_FLAT_CONFIG: false # Force ESLint to use the older config style
        run: yarn lint
        working-directory: ./webapp
